name: Publish chatwoot Docker image on release

on:
  push:
    tags:
      - chatwoot-**
    paths:
      - "chatwoot/**"
      - ".github/**"
  workflow_dispatch:

jobs:
  push_to_registries:
    permissions:
      contents: read
      packages: write
      id-token: write
    name: Push chatwoot image to repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: coreharbor.kubernetes.midnightthoughts.space
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: coreharbor.kubernetes.midnightthoughts.space/chatwoot/chatwoot
          tags: type=sha,format=long

      - name: Strip enterprise code
        run: |
          rm -rf chatwoot/enterprise
          rm -rf chatwoot/spec/enterprise

      - name: Set Chatwoot edition
        run: |
          echo -en '\nENV CW_EDITION="ce"' >> chatwoot/docker/Dockerfile

      - name: Build and push
        id: build_and_push
        uses: docker/build-push-action@v4
        with:
          push: true
          context: chatwoot
          file: chatwoot/docker/Dockerfile
          sbom: true
          provenance: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}

      - name: Sign the images with GitHub OIDC Token
        env:
          DIGEST: ${{ steps.build_and_push.outputs.digest }}
          TAGS: ${{ steps.docker_meta.outputs.tags }}
        run: cosign sign --yes "${TAGS}@${DIGEST}"
